In [28]:
from torch.utils.data import Dataset, DataLoader

In [53]:
class AudioDataset(Dataset):
    
    def __init__(self, audio_fajlovi):
        self.audio_fajlovi = audio_fajlovi
    
    def __getitem__(self, idx):
        return self.audio_fajlovi[idx]
    
    def __len__(self):
        return len(self.audio_fajlovi)

In [54]:
dataset = AudioDataset([1,2,3,4,5,6])

In [55]:
print(dataset[1])
print(len(dataset))

2
6


In [56]:
loader = DataLoader(dataset, shuffle=True, batch_size=3)

In [62]:
for epoch in range(10):
    print(f"Starting epoch {epoch+1}!")
    for element in loader:
        predictions = model(element)
        print("=======")

Starting epoch 1!
tensor([2, 5, 3])
tensor([1, 4, 6])
Starting epoch 2!
tensor([4, 2, 6])
tensor([1, 3, 5])
Starting epoch 3!
tensor([5, 4, 2])
tensor([6, 1, 3])
Starting epoch 4!
tensor([6, 1, 3])
tensor([5, 2, 4])
Starting epoch 5!
tensor([3, 4, 5])
tensor([1, 2, 6])
Starting epoch 6!
tensor([5, 3, 1])
tensor([4, 2, 6])
Starting epoch 7!
tensor([2, 1, 3])
tensor([4, 6, 5])
Starting epoch 8!
tensor([4, 6, 5])
tensor([1, 2, 3])
Starting epoch 9!
tensor([6, 2, 1])
tensor([3, 5, 4])
Starting epoch 10!
tensor([6, 2, 5])
tensor([1, 4, 3])


In [66]:
X = [1,2,3,4,5]
Y = []
for e in X:
    if e % 2 == 0:
        Y.append(e + 2)
    else:
        Y.append(e - 2)
print(Y)

[-1, 4, 1, 6, 3]


In [68]:
Y = [e+2 if e % 2 == 0 else e - 2 for e in X]
print(Y)

[-1, 4, 1, 6, 3]
